### ISSUE TITLE
hugo executable is broken on macOS 10.13.2

### ISSUE THREAD

**Issue by broomburgo** [facile-it/facile-it.github.io#16]
Calling `./hugo` from the project folder results in the following message:

`./hugo: line 10:   813 Segmentation fault: 11  ./bin/hugo_0.16_osx_amd64 "$@"`

The latest hugo version (0.31.1) installed via homebrew works as expected.

**Comment by Jean85** [comment]
The hugo executable is committed in the repo. If you can confirm that the new version builds the site correctly, you can update and commit it! :+1:

**Comment by broomburgo** [comment]
ref. #17
