### ISSUE TITLE
Update the theme

### ISSUE THREAD

**Issue by Jean85** [facile-it/facile-it.github.io#19]
It would be nice to update the theme, pulling the upstream changes [from the original repo](https://github.com/jpescador/hugo-future-imperfect). To do that, we have to recover the point from which we forked it, and merge the diffs before reapplying our customizations. Maybe we can even leverage the new Hugo version installed with #17 & #18 to fix or improve them.

If I have to guess, the last commit from which we diverged/forked should be https://github.com/jpescador/hugo-future-imperfect/commit/2db677fe337a2bab43b776318559f86db9316daf, since the next one comes from this big PR: https://github.com/jpescador/hugo-future-imperfect/pull/48 which restarted the development after a long hiatus.

@alexmanno maybe you're up for it?

**Comment by salvatorecordiano** [comment]
@Jean85, can we close this?

**Comment by Jean85** [comment]
Yes, it was already done by @alexmanno
