### ISSUE TITLE
Long strings break the template layout

### ISSUE THREAD

**Issue by Algatux** [facile-it/facile-it.github.io#4]
long strings on a single line and without spaces, as for example the token in the jwt article, will break the template layout.

**Comment by Jean85** [comment]
Unfortunately, it seems an issue of the template we are using. I could try to open an issue on the relative report.

**Comment by Jean85** [comment]
The template's author said that he already aknowledge the issue, and he has no immediate solution.

For now, I've added a fixed `max-width` to the `<pre>` elements.
