### ISSUE TITLE
Wrong preview on LinkedIn post

### ISSUE THREAD

**Issue by AndreaRR18** [facile-it/facile-it.github.io#41]
When we publish a new article on our blog we cannot see the thumbnail image.
On twitter the logo preview is good but on LinkedIn it is too big.

One possible solution is to show a thumbnail instead of the Facile logo.
This article has a cover image (https://engineering.facile.it/blog/eng/from-zero-to-infinite-the-final-keyword/) but it is not visible.
Please @ Jean85 @salvatorecordiano, if you can, we need to fix this on our blog.

<img width="553" alt="Screenshot 2020-12-14 at 08 51 25" src="https://user-images.githubusercontent.com/23659024/102054355-9025c200-3de9-11eb-9ef7-aa6d05e978fc.png">
<img width="597" alt="Screenshot 2020-12-14 at 08 52 10" src="https://user-images.githubusercontent.com/23659024/102054416-a9c70980-3de9-11eb-8dc1-37716f86b84a.png">

**Comment by salvatorecordiano** [comment]
@Jean85 I'm proposing branch 2012_wrong_preview to fix this issue. Can you check, please?

**Comment by Jean85** [comment]
I personally don't know of a way to test this...

**Comment by salvatorecordiano** [comment]
@salvatorecordiano I was able to reproduce the issue. In our old code we generate open graph fields statically. No It's dynamic

**Comment by Jean85** [comment]
@salvatorecordiano in the case of the article with the cover image (https://github.com/facile-it/facile-it.github.io/blame/source/content/blog/eng/from-zero-to-infinite-the-final-keyword.md#L10), it produces
```<meta name="twitter:image:src" content="http://localhost:1313/images/social/twitter-card-logo.png">```
which is still the generic one

For reference, this is the proposed branch with the fix from @salvatorecordiano: https://github.com/facile-it/hugo-future-imperfect/commits/2012_preview_update

**Comment by salvatorecordiano** [comment]
Hi @Jean85,
in the post https://github.com/facile-it/facile-it.github.io/blame/source/content/blog/eng/from-zero-to-infinite-the-final-keyword.md, the usage of `twitterImage` property is wrong, because it doesn't refer to an image.

If you try with this article https://github.com/facile-it/facile-it.github.io/blob/source/content/blog/eng/realpath-cache-is-it-all-php-opcache-s-fault.md, it works fine!

Thanks
